#
###################################
# Site wide configuration
####################################
#
title: Joe
email:
description: Be a warrior not a worrier.
url: # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
    sass_dir: _sass
    sourcemap: true
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Yue Zhou (Joe)
  avatar: s2.png
  job: "Web Developer"
  bio: "I am an enthusiastic and high-achieving developer, who regards building high-quality and valuable web systems as the very essence of my career. I have exceptional technical and analytical skills, with experience in web development. I love to combine bunch of suitable technologies to realise some amazing ideas and taking the project to the next stage."
  email: ashzhouyue@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: zhou.yue.315
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ZYMoridae
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: yue-zhou-8b8a49134
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: 76561198056927078
  dribbble: #username
  youtube: #username
  soundcloud: zhou-yue
  weibo: #username
  flickr: #username
  codepen: #username
